[project]
name = "ansible-common"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
 "ansible-dev-tools>=25.10.0",
]

[dependency-groups]
dev = [
    "yamllint>=1.37.1",
]
