---
# Ansible role to set the system locale

- name: "Validate required variables"
  ansible.builtin.assert:
    that:
      - "system_locale_name is defined"
    msg: "Missing a required variable"

- name: "Install locales package"
  ansible.builtin.apt:
    name: "locales"
    state: "present"
    update_cache: true

- name: "Ensure the correct locale is generated"
  community.general.locale_gen:
    name: "{{ system_locale_name }}"
    state: "present"
