---
- name: "Install dependencies"
  ansible.builtin.apt:
    name:
      - "ca-certificates"
      - "curl"
      - "python3-debian"
    state: "present"
    update_cache: true

- name: "Add docker GPG key"
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: "/etc/apt/keyrings/docker.asc"
    mode: "0644"

- name: "Add or remove Docker repository"
  ansible.builtin.deb822_repository:
    name: "docker"
    types: "deb"
    uris: "https://download.docker.com/linux/debian"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: "stable"
    signed_by: "/etc/apt/keyrings/docker.asc"
    state: "present"

- name: "Install Docker"
  vars:
    _v: >-
      {{ '=' + docker_install_version
      if docker_install_version is defined else '' }}
  ansible.builtin.apt:
    name:
      - "docker-ce{{ _v }}"
      - "docker-ce-cli{{ _v }}"
      - "containerd.io"
      - "docker-buildx-plugin"
      - "docker-compose-plugin"
    state: "present"
    update_cache: true

- name: "Ensure Docker service is started"
  ansible.builtin.systemd:
    name: "docker"
    state: "started"
    enabled: true

- name: "Run the hello-world container to verify installation"
  ansible.builtin.command:
    argv:
      - "docker"
      - "run"
      - "--rm"
      - "hello-world"
  changed_when: false
